version: '3'

services:
  flask_app:
    image: stanny880913/yolo_flask_app:1.0.0
    restart: always
    build: ./flask_app
    ports:
      - 8000:8000
    command: gunicorn -w 1 --log-level=debug -b 0.0.0.0:8000 app:app

  nginx:
    image: stanny880913/yolo_flask_nginx:1.0.0
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask_app
    volumes:
      - ./flask_app/static:/etc/nginx/static
